imports:
  - { resource: forms.yml }
  - { resource: data_fixtures.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ShopBundle\Controller\:
    resource: '../../Controller/'
    public: true
    tags: ['controller.service_arguments']

  Shopsys\ShopBundle\Component\:
    resource: '../../Component/*/*.php'

  Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory: ~

  Shopsys\FrameworkBundle\Model\Order\OrderFlowFactoryInterface: '@Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory'
